pose_patterns = [
        [{"LOWER": "fist"}],
        [{"LOWER": "fist2"}],
        [{"LOWER": "five"}, {"LOWER": "fingers"}, {"LOWER": "pinch"}],
        [{"LOWER": "four"}, {"LOWER": "fingers"}, {"LOWER": "pinch"}],
        [{"LOWER": "full"}, {"LOWER": "pinch"}],
        [{"LOWER": "gun"}, {"LOWER": "click"}],
        [{"LOWER": "gun"}, {"LOWER": "click2"}],
        [{"LOWER": "gun"}, {"LOWER": "click3"}],
        [{"LOWER": "hand"}, {"LOWER": "backward"}],
        [{"LOWER": "hand"}, {"LOWER": "forward"}],
        [{"LOWER": "index"}, {"LOWER": "pinch"}],
        [{"LOWER": "index"}],
        [{"LOWER": "palm"}, {"LOWER": "stop"}],
        [{"LOWER": "peace"}],
        [{"LOWER": "pinky"}, {"LOWER": "2"}, {"LOWER": "up"}],
        [{"LOWER": "pinky"}, {"LOWER": "3"}, {"LOWER": "up"}],
        [{"LOWER": "pinky"}, {"LOWER": "up"}, {"LOWER": "education"}],
        [{"LOWER": "pinky"}, {"LOWER": "up"}],
        [{"LOWER": "punch"}, {"LOWER": "heavy"}],
        [{"LOWER": "punch"}, {"LOWER": "light"}],
        [{"LOWER": "shoot"}],
        [{"LOWER": "three"}, {"LOWER": "fingers"}, {"LOWER": "pinch"}, {"LOWER": "hand"}, {"LOWER": "closed"}],
        [{"LOWER": "three"}, {"LOWER": "fingers"}, {"LOWER": "pinch"}],
        [{"LOWER": "three"}, {"LOWER": "fingers"}, {"LOWER": "release"}, {"LOWER": "hand"}, {"LOWER": "closed"}],
        [{"LOWER": "three"}, {"LOWER": "fingers"}],
        [{"LOWER": "thumb"}, {"LOWER": "index"}, {"LOWER": "pinch"}, {"LOWER": "hand"}, {"LOWER": "closed"}],
        [{"LOWER": "thumb"}, {"LOWER": "index"}, {"LOWER": "pinch"}],
        [{"LOWER": "thumb"}, {"LOWER": "index"}, {"LOWER": "release"}, {"LOWER": "hand"}, {"LOWER": "closed"}],
        [{"LOWER": "thumb"}, {"LOWER": "index"}, {"LOWER": "release"}],
        [{"LOWER": "thumb"}, {"LOWER": "middle"}, {"LOWER": "pinch"}],
        [{"LOWER": "thumb"}, {"LOWER": "middle"}, {"LOWER": "release"}],
        [{"LOWER": "thumb"}, {"LOWER": "pinky"}, {"LOWER": "pinch"}],
        [{"LOWER": "thumb"}, {"LOWER": "pinky"}, {"LOWER": "release"}],
        [{"LOWER": "thumb"}, {"LOWER": "ring"}, {"LOWER": "pinch"}],
        [{"LOWER": "thumb"}, {"LOWER": "ring"}, {"LOWER": "release"}],
        [{"LOWER": "thumb"}, {"LOWER": "up"}],
    ]

# Creating a list where each element's name is derived from the gesture patterns
gesture_array = ['_'.join([item['LOWER'] for item in pattern]) for pattern in pose_patterns]

print(gesture_array)