TRAIN_DATA = [
    ("I want to play Minecraft", {"entities": [(15, 24, "GAME")]}),
    ("Start playing Minecraft with my right hand", {"entities": [(14, 23, "GAME"), (32, 42, "HAND")]}),
    ("place a block down", {"entities": []}),
    ("I love Minecraft", {"entities": []}),
    ("hold my fist to place a block down", {"entities": [(8, 12, "GESTURE")]}),
    ("Let's play Rocket League", {"entities": [(11, 24, "GAME")]}),
    ("I use the joystick to drive in Horizon", {"entities": [(31, 38, "GAME"), (22, 27, "GESTURE")]}),
    ("FIFA is best played with a controller", {"entities": [(0, 4, "GAME"), (27, 37, "GESTURE")]}),
    ("Playing Tetris requires quick rotations", {"entities": [(8, 14, "GAME")]}),
    ("Cast a spell in Final Fantasy", {"entities": [(16, 29, "GAME")]}),
    ("Score a goal in FIFA using my feet", {"entities": [(16, 20, "GAME")]}),
    ("Build a tower in Minecraft with blocks", {"entities": [(17, 26, "GAME")]}),
    ("Launch the ball in Rocket League with a flip", {"entities": [(19, 32, "GAME")]}),
    ("Rotate pieces in Tetris quickly", {"entities": [(17, 23, "GAME"), (0, 6, "GESTURE")]}),
    ("Drive through the field in Horizon with speed", {"entities": [(27, 34, "GAME"), (0, 5, "GESTURE")]}),
    ("Perform a free kick in FIFA", {"entities": [(23, 27, "GAME"), (10, 19, "GESTURE")]}),
    ("Summon your ally in Final Fantasy", {"entities": [(20, 33, "GAME")]}),
]
